accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'login/$', auth_views.LoginView.as_view(
        template_name='accounts/login.html'), name='login'),
    url(r'logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'signup/$', views.SignUp.as_view(), name='signup'),
]

alFurqaan/urls.py
from django.contrib import admin
from django.urls import path
from inventory import views
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view(), name='home'),
    url(r'^inventory/', include('inventory.urls', namespace='inventory')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
]

inventory/urls.py
from django.conf.urls import url
from . import views

app_name = 'inventory'

urlpatterns = [
    url('^$', views.ItemListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.ItemDetailView.as_view(), name='detail'),
    url(r'^create-item/$', views.ItemCreateView.as_view(), name='create-item'),
    url(r'^update/(?P<pk>\d+)/$', views.ItemUpdateView.as_view(),
        name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.ItemDeleteView.as_view(),
        name='delete'),
    url(r'^create-trans/$', views.TransactionCreateView.as_view(),
        name='create-trans'),
    url('^trans-list/$', views.TransactionListView.as_view(),
        name='trans-list'),
    url(r'^trans-list/(?P<pk>\d+)/$', views.TransactionDetailView.as_view(),
        name='trans-detail'),
    url(r'^print-reciept/(?P<pk>\d+)/$', views.PrintReceipt.as_view(),
        name='print-receipt'),
    url(r'^update-trans/(?P<pk>\d+)/$', views.TransactionUpdateView.as_view(),
        name='update-trans'),
    url(r'^delete-trans/(?P<pk>\d+)/$', views.TransactionDeleteView.as_view(),
        name='delete-trans'),
    url(r'^trans-list/my-trans/(?P<username>[-\w]+)/$',
        views.CashierTransactionList.as_view(), name='my-trans'),
    url(r'^create_cashierLog/$', views.LogCreateView.as_view(),
        name='create_cashierLog'),
    url(r'^list_cashierLog/', views.LogListView.as_view(),
        name='list_cashierLog'),
    url(r'^list_cashierLog/(?P<pk>\d+)/$', views.LogDetailView.
        as_view(), name='detail_cashierLog'),
    url(r'^update_cashierLog/(?P<pk>\d+)/$', views.LogUpdateView.
        as_view(), name='update_ashierLog'),
    url(r'^delete_cashierLog/(?P<pk>\d+)/$', views.LogDeleteView.
        as_view(), name='delete_cashierLog'),
]

inventory/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth import get_user_model
# from django.template.defaultfilters import slugify

# Create your models here.

User = get_user_model()


class Manufacturer(models.Model):
    maker = models.CharField(max_length=20)

    def __str__(self):
        return self.maker


class Item(models.Model):
    item_id = models.AutoField(primary_key=True)
    item_name = models.CharField(max_length=15)
    maker = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    priceByDefault = models.IntegerField(default=1, blank=True)
    # slug = models.SlugField(null=True, unique=True)

    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse('inventory:detail', kwargs={'pk': self.pk})

    """
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.item_name)
        return super().save(*args, **kwargs)
    """


"""
class Customer(models.Model):
    name = models.CharField(max_length=50)
    address = models.TextField(max_length=100)
    phone = models.CharField(max_length=11)
    email = models.EmailField()
"""


class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    trans_id = models.AutoField(primary_key=True)
    quantity = models.IntegerField()
    time = models.DateTimeField(default=timezone.now)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    sellPrice = models.IntegerField(default=1)
    imei = models.CharField(max_length=15)
    custName = models.CharField(max_length=50)
    custAdd = models.TextField(max_length=100)
    cusPhone = models.CharField(max_length=11, blank=True)
    custEmail = models.EmailField(blank=True)
    note = models.TextField(max_length=200, blank=True)

    def __str__(self):
        return ("%s , %s , %s, %s" % (self.item.item_name, self.item.quantity,
                self.sellPrice, self.time))

    def get_absolute_url(self):
        return reverse('inventory:trans-detail', kwargs={'pk': self.pk})


class Log(models.Model):
    log_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity_assigned = models.IntegerField(default=0)
    quantity_sold = models.IntegerField(default=0)
    quantity_inStock = models.IntegerField(default=0)
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.item.item_name

    def get_absolute_url(self):
        return reverse('inventory:detail_cashierLog', kwargs={'pk': self.pk})

inventory/views.py
from django.shortcuts import render
from django.contrib import messages
from easy_pdf.views import PDFTemplateResponseMixin
from django.http import Http404
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from inventory import models
from inventory.models import Log, Item, Transaction
from django.views.generic import (TemplateView, ListView, DetailView,
                                  CreateView, UpdateView, DeleteView)

# Create your views here.

User = get_user_model()


class TestPage(TemplateView):
    template_name = 'test.html'


class ThanksPage(TemplateView):
    template_name = 'thanks.html'


class IndexView(TemplateView):
    template_name = 'index.html'


class ItemListView(ListView):
    context_object_name = 'items'
    model = models.Item


class ItemDetailView(DetailView):
    context_object_name = 'item_detail'
    model = models.Item
    template_name = 'inventory/item_detail.html'


class ItemCreateView(CreateView):
    fields = ('item_name', 'maker', 'quantity', 'priceByDefault')
    model = models.Item


class ItemUpdateView(UpdateView):
    fields = ('quantity', 'priceByDefault')
    model = models.Item


class ItemDeleteView(DeleteView):
    model = models.Item
    success_url = reverse_lazy('inventory:list')


class TransactionCreateView(LoginRequiredMixin, CreateView,):
    fields = ('quantity', 'item', 'sellPrice', 'imei', 'custName', 'custAdd',
              'cusPhone', 'custEmail', 'note')
    model = models.Transaction

    # def cashierDataMgmt(self, *args, **kwargs,):
    #    if self.item == log.item and self.quantity < log.quantity_assigned:
    #        log.quantity_sold += self.quantity
    #    return log.quantity_sold
    # def sortData(request, self, *args, **kwargs):
    # import pdb
    # pdb.set_trace()

    def sortData(self, request, quantity, log_id):
        log = Log.objects.get(pk=log_id)
        quantity = request.POST.get('quantity')

        if self.item.item_id == log.item.item_id and self.quantity < log.quantity_inStock:
            log.quantity_sold += quantity
        else:
            messages.warning(request, 'The quantity you intend to sell out is lower than the pieces in your stock')
        log.save()
        return log.quantity_sold

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.sortData(self.request, 'quantity', Log.log_id)
        self.object.save()
        return super().form_valid(form)


"""
def transactionView(request):
    item = Item.objects.get(pk=Item.item_id)
    quantity = request.POST.get('quantity')
    sellPrice = request.POST.get('sellPrice')
    imei = request.POST.get('imei')
    custName = request.POST.get('custName')
    custAdd = request.POST.get('custAdd')
    cusPhone = request.POST.get('cusPhone')
    custEmail = request.POST.get('custEmail')
    note = request.POST.get('note')

    transaction = Transaction(item=item, quantity=quantity,
                              sellPrice=sellPrice, imei=imei,
                              custName=custName, custAdd=custAdd,
                              cusPhone=cusPhone, custEmail=custEmail,
                              note=note)

    log = Log.objects.get(pk=Log.log_id)
    object.user = request.user
    if item.item_id == log.item.item_id and quantity < log.quantity_inStock:
        log.quantity_sold += quantity
    else:
        messages.warning(request, 'The quantity you intend to sell out is lower than the pieces in your stock')
    log.save()
    transaction.save()
    # return log.quantity_sold
    return render(request, 'inventory/transaction_form.html',
                  {'transaction': transaction})
"""


class TransactionListView(LoginRequiredMixin, ListView):
    context_object_name = 'transactions'
    model = models.Transaction


class TransactionDetailView(LoginRequiredMixin, DetailView):
    context_object_name = 'transaction_detail'
    model = models.Transaction
    template_name = 'inventory/transaction_detail.html'


class PrintReceipt(PDFTemplateResponseMixin, DetailView, LoginRequiredMixin):
    model = models.Transaction
    template_name = 'inventory/trans_receipt.html'

    """
    def print(self):
        self.object = self.get_object()
        return self.object
    """


class TransactionUpdateView(LoginRequiredMixin, UpdateView):
    fields = ('quantity', 'sellPrice', 'custName', 'custAdd', 'cusPhone',
              'custEmail')
    model = models.Transaction


class TransactionDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Transaction
    success_url = reverse_lazy('inventory:trans-list')


class CashierTransactionList(LoginRequiredMixin, ListView):
    model = models.Transaction
    template_name = 'inventory/log_list.html'

    def get_queryset(self):
        try:
            self.transaction.user = User.objects.prefetch_related(
                'transactions').get(username__iexact=self.kwargs.get(
                    'username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.transaction_user.transactions.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['transaction_user'] = self.transaction_user
        return context


class LogCreateView(LoginRequiredMixin, CreateView):
    fields = ('user', 'item', 'quantity_assigned', 'quantity_sold', 'date')
    model = models.Log

    """
    def get_remainder(self):
        log.quantity_inStock = log.quantity_assigned - log.quantity_sold
        return log.quantity_inStock
    """


class LogDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Log
    success_url = reverse_lazy('inventory:list_cashierLog')


class LogUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Log
    fields = ('quantity_assigned')


class LogListView(LoginRequiredMixin, ListView):
    model = models.Log
    context_object_name = 'logs'


class LogDetailView(LoginRequiredMixin, DetailView):
    model = models.Log
    context_object_name = 'cashier_daily_log_detail'

templates/inventory/cashierDL_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block body_block %}
<h1>Delete {{log.item_name}}</h1>
<form method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'inventory:detail_cashierLog' pk=log.pk %}">Cancel</a>
</form>
{% endblock %}
    

templates/inventory/cashierDL_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block body_block %}

    
    {% if user.is_authenticated %}
        <div class="jumbotron">
            <h2>Item Sales Details</h2>
            <p>Item: {{cashier_daily_log_detail.item}}</p>
            <p>Quantity taken for the day: {{cashier_daily_log_detail.quantity_assigned}}</p>
            <p>Quantity sold: {{cashier_daily_log_detail.quantity_sold}}</p>
            <p>Quantity remaining: {{cashier_daily_log_detail.quantity_inStock}}</p>
        </div>
        <div class="container">
                <p><a href="{% url 'inventory:update_cashierLog' pk=cashier_daily_log_detail.pk %}" class="btn btn-warning">Update</a>
                   <a href="{% url 'inventory:delete_cashierLog' pk=cashier_daily_log_detail.pk %}" class="btn btn-warning">Delete</a></p>
        </div>
    {% endif %}
        

{% endblock %}
    

templates/inventory/cashier_trans_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block body_block %}
<div class="col-md-4">
    <h1>{{ transaction_user.username }}</h1>
    <p>Transactions History</p>
</div>
<div class="col-md-8">
    
    {% for transaction in transactions %}
        

        <div class="post media">
	
	<div class="media-body">
		<strong>{{ transaction.user.username }}</strong>
		<h5 class="media-heading">
			<span class="username"><a href="{% url 'transactions:for_user' username=transaction.user.username %}">{{ transaction.user.username }}</a></span>
			<time class="time"><a href="{% url 'inventory:trans-detail' username=transaction.user.username pk=transaction.pk %}">{{ transaction.time }}</a></time>
		</h5>




		<div class="media-footer">
			{% if user.is_authenticated and transacton.user == user and not hide_delete %}
				<a href="{% url 'inventory:delete-trans' pk=transaction.pk %}" title="delete" class="btn btn-simple">
					<span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
				</a>
			{% endif %}
		</div>
	</div>
</div>



    {% endfor %}
        
</div>
{% endblock %}
    

templates/inventory/item_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block body_block %}


{% if user.is_authenticated %}
    
    <h1>Delete {{item.item_name}}</h1>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'inventory:detail' pk=item.pk %}">Cancel</a>
    </form>
    {% endif %}
    
{% endblock %}

templates/inventory/item_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block body_block %}
    
    {% if user.is_authenticated %}
        
    <div class="jumbotron">
        <h2>Item details</h2>
        <p>Name: {{item_detail.item_name}}</p>
        <p>Manufacturer: {{item_detail.maker}}</p>
        <p>Quantity in Stock: {{item_detail.quantity}}</p>
        <p>Price: {{item_detail.priceByDefault}}</p>
    </div>

    <div class="container">
        <p><a href="{% url 'inventory:update' pk=item_detail.pk %}" class="btn btn-warning">Update</a>
           <a href="{% url 'inventory:delete' pk=item_detail.pk %}" class="btn btn-warning">Delete</a></p>
    </div>
    
    {% endif %}

{% endblock %}

templates/inventory/item_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block body_block %}


{% if user.is_authenticated %}
    
    <h1>
        
        {% if not form.instance.pk %}
            Create/Add Item Into Stock
            {% else %}
            Update Item
        {% endif %}
            
    </h1>

    <form action="" method="POST">
        {% csrf_token %}
        
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>

    {% endif %}
{% endblock %}

templates/inventory/item_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block body_block %}

{% if user.is_authenticated %}
    
    {% for item in items %}
        <h2><li><a href="{{item.item_id}}">{{item.item_name}}</a></li></h2>
    {% endfor %}
        
    {% endif %}

    <div class="container">
        <p><a href="{% url 'inventory:create-item' %}" class="btn btn-primary">New Item</a></p>
    </div>

{% endblock %}

templates/inventory/log_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block body_block %}

{% if user.is_authenticated %}
    
    <h1>
        
        {% if not form.instance.pk %}
            Create/Add Item Into Cashier Daily Stock
            {% else %}
            Update Cashier Daily Stock
        {% endif %}
            
    </h1>

    <form action="" method="POST">
        {% csrf_token %}
        
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>

    {% endif %}

{% endblock %}
    

templates/inventory/log_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block body_block %}

{% if user.is_authenticated %}
<div class="table-resposive">
    <table class="table table-bordered table-condensed table-hover">
        <h1>CASHIER DAILY LOG</h1>
            <thead>
                <tr>
                    <th>S/N</th>
                    <th>ITEMS</th>
                    <th>QUANTITY ASSIGNED</th>
                    <th>QUANTITY SOLD</th>
                    <th>QUANTITY IN STOCK</th>
                </tr>
            {% for log in logs %}
                <tr>
                    <td><h4>{{log.log_id}}</h4></td>
                    <td><h4><a href="{{log.log_id}}">{{log.item}}</a></h4></td>
                    <td><h4>{{log.quantity_assigned}}</h4></td>
                    <td><h4>{{log.quanity_sold}}</h4></td>
                    <td><h4>{{log.quantityinStock}}</h4></td>
                </tr>
            {% endfor %}
    </table>
</div>      
    
        
    {% endif %}

    <div class="container">
        <p><a href="{% url 'inventory:create-item' %}" class="btn btn-primary">New Item</a></p>
    </div>


{% endblock %}
    

templates/inventory/trans_receipt.html
{% load bootstrap3 %}

<div class="jumbotron">
    <h2>Transaction details</h2>
    <p>Cashier: {{transaction.user}}</p>
    <p>Name: {{transaction.custName}}</p>
    <p>Address: {{transaction.custAdd}}</p>
    <p>Item: {{transaction.item}}</p>
    <p>Quantity: {{transaction.quantity}}</p>
    <p>IMEI: {{transaction.imei}}</p>
    <p>Amount Paid: {{transaction.sellPrice}}</p>
</div>

templates/inventory/transaction_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block body_block %}

{% if user.is_authenticated %}

    <h1>Delete {{transaction.item_name}} from transactions?</h1>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'inventory:trans-detail' pk=transaction.pk %}">Cancel</a>
    </form>
        
{% endif %}

{% endblock %}

templates/inventory/transaction_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block body_block %}
    

{% if user.is_authenticated %}
    

    
    <div class="jumbotron">
        <h2>Transaction details</h2>
        <p>Name: {{transaction_detail.custName}}</p>
        <p>Address: {{transaction_detail.custAdd}}</p>
        <p>Item: {{transaction_detail.item}}</p>
        <p>Quantity: {{transaction_detail.quantity}}</p>
        <p>IMEI: {{transaction_detail.imei}}</p>
        <p>Amount Paid: {{transaction_detail.sellPrice}}</p>
    </div>

    <div class="container">
        <p><a href="{% url 'inventory:print-receipt' pk=transaction_detail.pk %}" class="btn btn-warning">Print Receipt</a>
           <a href="{% url 'inventory:update-trans' pk=transaction_detail.pk %}" class="btn btn-warning">Update</a>
           <a href="{% url 'inventory:delete-trans' pk=transaction_detail.pk %}" class="btn btn-warning">Delete</a></p>
    </div>

    {% endif %}
    
{% endblock %}

templates/inventory/transaction_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block body_block %}


{% if user.is_authenticated %}
    
    
    <h1>
        
        {% if not form.instance.pk %}
            Transaction Page
            {% else %}
            Update Transaction
        {% endif %}
            
    </h1>

    <form action="" method="POST">
        {% csrf_token %}
        
        {{ form.as_p }}

        {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
            
            
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>


    
    <!-- 
    <script>
function logBookMgmt(trans_item, log_item, log_inStock) {
    var trans_item = transaction.item.item_name
    var log_item = log.item.item_name
    var log_inStock = log.quantity_inStock
    var trans_quantity = transaction.quantity
    var log_quantity = log.quantity_assigned

    if (trans_item == log_item && trans_quantity < log_quantity) {
        log_inStock += trans_quantity
    } else {
        alert("The quantity you are selling out is lower than the quantity in your stock. Contact the admin to get more of this particular item.")
    }
    return log_inStock
}
    </script>
                -->

    {% endif %}
            

{% endblock %}

templates/inventory/transaction_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block body_block %}
    
    {% if user.is_authenticated %}
        
    
        
    {% for transaction in transactions %}
        <h2><li><a href="{{transaction.trans_id}}">{{transaction.item}}</a></li></h2>
    {% endfor %}

    <div class="container">
        <p><a href="{% url 'inventory:create-trans' %}" class="btn btn-primary">New Transaction</a></p>
    </div>
    
    {% endif %}


{% endblock %}

    