accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'login/$', auth_views.LoginView.as_view(
        template_name='accounts/login.html'), name='login'),
    url(r'logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'signup/$', views.SignUp.as_view(), name='signup'),
]

alFurqaan/urls.py
from django.contrib import admin
from django.urls import path
from inventory import views
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view(), name='home'),
    url(r'^inventory/', include('inventory.urls', namespace='inventory')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
]

inventory/urls.py
from django.conf.urls import url
from . import views

app_name = 'inventory'

urlpatterns = [
    url('^$', views.ItemListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.ItemDetailView.as_view(), name='detail'),
    url(r'^create-item/$', views.ItemCreateView.as_view(), name='create-item'),
    url(r'^update/(?P<pk>\d+)/$', views.ItemUpdateView.as_view(),
        name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.ItemDeleteView.as_view(),
        name='delete'),
    url(r'^create-trans/$', views.TransactionCreateView.as_view(),
        name='create-trans'),
    url('^trans-list/$', views.TransactionListView.as_view(),
        name='trans-list'),
    url(r'^trans-list/(?P<pk>\d+)/$', views.TransactionDetailView.as_view(),
        name='trans-detail'),
    url(r'^print-reciept/(?P<pk>\d+)/$', views.PrintReceipt.as_view(),
        name='print-receipt'),
    url(r'^update-trans/(?P<pk>\d+)/$', views.TransactionUpdateView.as_view(),
        name='update-trans'),
    url(r'^delete-trans/(?P<pk>\d+)/$', views.TransactionDeleteView.as_view(),
        name='delete-trans'),
    url(r'^trans-list/my-trans/(?P<username>[-\w]+)/$',
        views.CashierTransactionList.as_view(), name='my-trans'),
    url(r'^create_cashierLog/$', views.LogCreateView.as_view(),
        name='create_cashierLog'),
    url(r'^list_cashierLog/', views.LogListView.as_view(),
        name='list_cashierLog'),
    url(r'^list_cashierLog/(?P<pk>\d+)/$', views.LogDetailView.
        as_view(), name='detail_cashierLog'),
    url(r'^update_cashierLog/(?P<pk>\d+)/$', views.LogUpdateView.
        as_view(), name='update_ashierLog'),
    url(r'^delete_cashierLog/(?P<pk>\d+)/$', views.LogDeleteView.
        as_view(), name='delete_cashierLog'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load bootstrap3 %}
    <title>al-furqaan</title>

    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'alFurqaan/css/master.css'%}">

</head>
<body>
    
    <div class="container">

        <nav class="navbar mynav navbar-default navbar-static-top" role="navigation" id="navbar">

            <a class="navbar-brand mynav" href="{% url 'home' %}">Al-Furqaan</a>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a class="navbar-brand" href="{% url 'inventory:list' %}">Items</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class="navbar-link" href="{% url 'inventory:trans-list' %}">Transactions</a></li>
                    <li><a class="navbar-link" href="{% url 'inventory:create_cashierLog' %}">Create Log</a></li>
                    <li><a class="navbar-link" href="{% url 'inventory:list_cashierLog' %}">Log Book</a></li>
                    
                    <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
                    <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
                {% endif %}
            </ul>
        </nav>
        <div class="container mycontent">

            {% block body_block %}
            
            {% endblock %}

        </div>
            
    </div>

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block body_block %}
    <div class="jumbotron">
        <h1>Al-Furqaan Home-Page</h1>
    </div>
{% endblock %}

templates/test.html
{% extends 'base.html' %}

{% block body_block %}


{% if user.is_authenticated %}

    <h1>Welcome {{ user.username }}; You are now logged in!</h1>

{% endif %}
    
    
{% endblock body_block %}
    

templates/thanks.html
{% extends 'base.html' %}

{% block body_bock %}
    
    <h1>You are Logged out of the system</h1>

{% endblock %}